### ISSUE TITLE
Quantity of products

### ISSUE THREAD

**Issue by rcj9719** [RahulPatkiWork/SmartAgro#7]
Can the quantity of products be made more continuous. For instance, if user wants 5 kg of Brinjal instead of 10kg.

**Comment by RahulPatkiWork** [comment]
> Can the quantity of products be made more continuous. For instance, if user wants 5 kg of Brinjal instead of 10kg.

Yes.
The quantity is a 'seller dependant' (and consequently customizable ) attribute,so the particular seller will determine how much minimum quantity of particular product he wishes to sell in one go.

However I'll update most of them to 1kg so that you can select integral quantities by simply updating the no.of items in cart!  :)
